---
name: Continuous Delivery

on:
  push:
    branches:
      - main # comentario

permissions: {}

jobs:
  delivery:
    name: Delivery
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulando CD
        uses: actions/upload-artifact@v4
        with:
          name: zipado
          path: |
            README.md
